#!/usr/bin/env python3
"""Generate LMC 8.4 R18 XML configs for POCO M3 Pro 5G (camellia / camellian)."""

from pathlib import Path
from xml.sax.saxutils import escape

OUT = Path(__file__).resolve().parent


def S(name, value):
    return f'    <string name="{escape(name)}">{escape(str(value))}</string>'


def B(name, value: bool):
    return f'    <boolean name="{escape(name)}" value="{str(value).lower()}" />'


def I(name, value: int):
    return f'    <int name="{escape(name)}" value="{int(value)}" />'


def SET(name, items):
    inner = "\n".join(f"        <string>{escape(str(x))}</string>" for x in items)
    return f'    <set name="{escape(name)}">\n{inner}\n    </set>'


# Libpatcher profiles (0-11). Stream 0 only — photo pipeline.
# Tuned for OmniVision OV48B (main, 12MP Quad-Bayer bin) + OV8856 (front)
# on MediaTek Dimensity 700 with no OIS and no Hexagon DSP.
PROFILES = {
    0: dict(
        title="Daily Natural",
        sharp_a="1.3125",
        sharp_b="1.0 (Default)",
        luma_a="1.0 (Default)",
        luma_b="1.0625",
        chroma_a="1.1875",
        chroma_b="1.125",
        sat="1.1875",
        contrast="0.040",
        contrast_black="1.125",
        clarity="1.125",
        edge="1.125",
        depth="1.125",
        mini="1.05",
        hdr_int="0.8125",
        light="1.0625",
        iso="4800",
        lut="2.0",
        vig="0",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.35",
        cf2="1.20",
        hdr_light="1.125",
        hdr_minus="-1.5",
        shadow="1.25",
        green="0.96",
        red="0.99",
        blue="1.02",
    ),
    1: dict(
        title="Night Sight",
        sharp_a="1.125",
        sharp_b="1.0 (Default)",
        luma_a="1.25",
        luma_b="1.25",
        chroma_a="1.375",
        chroma_b="1.25",
        sat="1.125",
        contrast="0.028",
        contrast_black="1.1875",
        clarity="1.0625",
        edge="1.0 (Default)",
        depth="1.0625",
        mini="1.00",
        hdr_int="0.50",
        light="1.1875",
        iso="8000",
        lut="4.0 (ON)",
        vig="0",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.50",
        cf2="1.35",
        hdr_light="1.375",
        hdr_minus="-1.0",
        shadow="1.50",
        green="0.95",
        red="0.98",
        blue="1.01",
    ),
    2: dict(
        title="Vivid Social",
        sharp_a="1.50",
        sharp_b="1.0625",
        luma_a="1.0 (Default)",
        luma_b="1.0625",
        chroma_a="1.125",
        chroma_b="1.125",
        sat="1.50",
        contrast="0.072",
        contrast_black="1.25",
        clarity="1.25",
        edge="1.1875",
        depth="1.1875",
        mini="1.08",
        hdr_int="1.0 (Default)",
        light="1.125",
        iso="4800",
        lut="2.0",
        vig="0.125",
        ct="16",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.40",
        cf2="1.25",
        hdr_light="1.25",
        hdr_minus="-2.0",
        shadow="1.375",
        green="0.97",
        red="1.00",
        blue="1.04",
    ),
    3: dict(
        title="Macro 2MP",
        sharp_a="1.75",
        sharp_b="1.125",
        luma_a="1.25",
        luma_b="1.25",
        chroma_a="1.375",
        chroma_b="1.25",
        sat="1.25",
        contrast="0.055",
        contrast_black="1.125",
        clarity="1.375",
        edge="1.25",
        depth="1.25",
        mini="1.10",
        hdr_int="0.75",
        light="1.125",
        iso="3200",
        lut="4.0 (ON)",
        vig="0",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.45",
        cf2="1.30",
        hdr_light="1.125",
        hdr_minus="-1.5",
        shadow="1.25",
        green="0.96",
        red="0.99",
        blue="1.02",
    ),
    4: dict(
        title="Portrait",
        sharp_a="1.25",
        sharp_b="1.0 (Default)",
        luma_a="1.125",
        luma_b="1.125",
        chroma_a="1.1875",
        chroma_b="1.125",
        sat="1.15",
        contrast="0.045",
        contrast_black="1.1875",
        clarity="1.0625",
        edge="1.0625",
        depth="1.25",
        mini="1.02",
        hdr_int="0.75",
        light="1.0625",
        iso="4000",
        lut="2.0",
        vig="0.20",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.30",
        cf2="1.15",
        hdr_light="1.125",
        hdr_minus="-1.5",
        shadow="1.25",
        green="0.96",
        red="0.98",
        blue="1.00",
    ),
    5: dict(
        title="Max Detail",
        sharp_a="1.625",
        sharp_b="1.125",
        luma_a="0.95",
        luma_b="1.0 (Default)",
        chroma_a="1.0625",
        chroma_b="1.0625",
        sat="1.1875",
        contrast="0.050",
        contrast_black="1.125",
        clarity="1.375",
        edge="1.25",
        depth="1.25",
        mini="1.12",
        hdr_int="0.875",
        light="1.0 (Default)",
        iso="3200",
        lut="1.0",
        vig="0",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.20",
        cf2="1.10",
        hdr_light="1.0625",
        hdr_minus="-1.5",
        shadow="1.125",
        green="0.96",
        red="0.99",
        blue="1.02",
    ),
    6: dict(
        title="Landscape Sky",
        sharp_a="1.4375",
        sharp_b="1.0625",
        luma_a="1.0 (Default)",
        luma_b="1.0625",
        chroma_a="1.125",
        chroma_b="1.125",
        sat="1.375",
        contrast="0.060",
        contrast_black="1.1875",
        clarity="1.25",
        edge="1.1875",
        depth="1.1875",
        mini="1.08",
        hdr_int="0.9375",
        light="1.0625",
        iso="3200",
        lut="2.0",
        vig="0.08",
        ct="16",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.35",
        cf2="1.20",
        hdr_light="1.1875",
        hdr_minus="-2.0",
        shadow="1.25",
        green="0.98",
        red="0.99",
        blue="1.06",
    ),
    7: dict(
        title="Indoor Mixed",
        sharp_a="1.25",
        sharp_b="1.0 (Default)",
        luma_a="1.1875",
        luma_b="1.1875",
        chroma_a="1.3125",
        chroma_b="1.25",
        sat="1.15",
        contrast="0.035",
        contrast_black="1.125",
        clarity="1.0625",
        edge="1.0625",
        depth="1.0625",
        mini="1.02",
        hdr_int="0.75",
        light="1.125",
        iso="4000",
        lut="3.0",
        vig="0",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.45",
        cf2="1.30",
        hdr_light="1.25",
        hdr_minus="-1.25",
        shadow="1.375",
        green="0.94",
        red="0.97",
        blue="1.00",
    ),
    8: dict(
        title="Selfie Natural",
        sharp_a="1.125",
        sharp_b="1.0 (Default)",
        luma_a="1.25",
        luma_b="1.1875",
        chroma_a="1.375",
        chroma_b="1.25",
        sat="1.10",
        contrast="0.030",
        contrast_black="1.0625",
        clarity="1.0 (Default)",
        edge="1.0 (Default)",
        depth="1.0625",
        mini="1.00",
        hdr_int="0.6875",
        light="1.125",
        iso="3200",
        lut="3.0",
        vig="0",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.40",
        cf2="1.25",
        hdr_light="1.1875",
        hdr_minus="-1.25",
        shadow="1.25",
        green="0.95",
        red="0.97",
        blue="1.01",
    ),
    9: dict(
        title="Selfie Beauty",
        sharp_a="1.0 (Default)",
        sharp_b="1.0 (Default)",
        luma_a="1.375",
        luma_b="1.25",
        chroma_a="1.4375",
        chroma_b="1.3125",
        sat="1.125",
        contrast="0.022",
        contrast_black="1.0625",
        clarity="0.95",
        edge="1.0 (Default)",
        depth="1.0 (Default)",
        mini="0.95",
        hdr_int="0.625",
        light="1.1875",
        iso="2500",
        lut="4.0 (ON)",
        vig="0.12",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.50",
        cf2="1.35",
        hdr_light="1.25",
        hdr_minus="-1.0",
        shadow="1.375",
        green="0.95",
        red="0.96",
        blue="1.00",
    ),
    10: dict(
        title="Document",
        sharp_a="2.0",
        sharp_b="1.25",
        luma_a="1.125",
        luma_b="1.125",
        chroma_a="1.25",
        chroma_b="1.1875",
        sat="0.90",
        contrast="0.095",
        contrast_black="1.375",
        clarity="1.50",
        edge="1.375",
        depth="1.25",
        mini="1.15",
        hdr_int="0.50",
        light="1.0 (Default)",
        iso="1600",
        lut="2.0",
        vig="0",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="0",
        en_col="1",
        cf1="1.25",
        cf2="1.15",
        hdr_light="1.0 (Default)",
        hdr_minus="-1.0",
        shadow="1.0 (Default)",
        green="1.00",
        red="1.00",
        blue="1.00",
    ),
    11: dict(
        title="Leica Contrast",
        sharp_a="1.375",
        sharp_b="1.0625",
        luma_a="1.0625",
        luma_b="1.125",
        chroma_a="1.1875",
        chroma_b="1.125",
        sat="1.0625",
        contrast="0.088",
        contrast_black="1.4375",
        clarity="1.1875",
        edge="1.125",
        depth="1.1875",
        mini="1.05",
        hdr_int="0.5625",
        light="0.9375",
        iso="4000",
        lut="2.0",
        vig="0.375",
        ct="14",
        awb="8",
        en_awb="0",
        en_cct="1",
        en_col="1",
        cf1="1.30",
        cf2="1.15",
        hdr_light="0.9375",
        hdr_minus="-2.0",
        shadow="1.0625",
        green="0.96",
        red="0.99",
        blue="1.01",
    ),
}


def lib_block(pid, p):
    sfx = f"_p{pid}_0"
    lines = [
        S(f"lib_profile_title_key{sfx}", p["title"]),
        S(f"lib_sharpness_a_key{sfx}", p["sharp_a"]),
        S(f"lib_sharpness_b_key{sfx}", p["sharp_b"]),
        S(f"lib_luma_a_key{sfx}", p["luma_a"]),
        S(f"lib_luma_b_key{sfx}", p["luma_b"]),
        S(f"lib_chroma_a_key{sfx}", p["chroma_a"]),
        S(f"lib_chroma_b_key{sfx}", p["chroma_b"]),
        S(f"lib_saturation_key{sfx}", p["sat"]),
        S(f"lib_contrast_1_key{sfx}", p["contrast"]),
        S(f"lib_contrast_black_key{sfx}", p["contrast_black"]),
        S(f"lib_clarity_key{sfx}", p["clarity"]),
        S(f"lib_sharpening_edge_key{sfx}", p["edge"]),
        S(f"lib_sharp_depth_1_key{sfx}", p["depth"]),
        S(f"lib_sharp_mini_key{sfx}", p["mini"]),
        S(f"lib_hdr_effect_intensity_key{sfx}", p["hdr_int"]),
        S(f"lib_lighting_key{sfx}", p["light"]),
        S(f"lib_iso_key{sfx}", p["iso"]),
        S(f"lib_lutnoisefix_key{sfx}", p["lut"]),
        S(f"lib_vignette_key{sfx}", p["vig"]),
        S(f"lib_pref_color_transform_key{sfx}", p["ct"]),
        S(f"lib_pref_awb_key{sfx}", p["awb"]),
        S(f"lib_enable_awb_key{sfx}", p["en_awb"]),
        S(f"lib_enable_cct_key{sfx}", p["en_cct"]),
        S(f"lib_enable_color_key{sfx}", p["en_col"]),
        S(f"lib_cf1_key{sfx}", p["cf1"]),
        S(f"lib_cf2_key{sfx}", p["cf2"]),
        S(f"lib_hdr_overall_lightness_key{sfx}", p["hdr_light"]),
        S(f"lib_hdr_range_minus_key{sfx}", p["hdr_minus"]),
        S(f"lib_shadow_compensation_key{sfx}", p["shadow"]),
        S(f"lib_pref_green_coeff_key{sfx}", p["green"]),
        S(f"lib_pref_red_coeff_key{sfx}", p["red"]),
        S(f"lib_pref_blue_coeff_key{sfx}", p["blue"]),
        S(f"lib_highlight_fix_key{sfx}", "1"),
        S(f"lib_highlight_fix_2_key{sfx}", "1"),
        S(f"lib_highlight_fix_3_key{sfx}", "1"),
        S(f"lib_hardjpgquality_key{sfx}", "97"),
        S(f"lib_override_cct_key{sfx}", "0"),
        S(f"lib_pref_wb_correction_key{sfx}", "0"),
    ]
    return lines


def build(variant: str):
    """variant: quality | fast"""
    hdrnet = variant == "fast"
    hdr_plus = "on" if hdrnet else "enhanced"
    frames_enh_back = "9" if hdrnet else "12"
    frames_enh_front = "7" if hdrnet else "9"
    frames_zsl = "7" if hdrnet else "9"
    frames_ns_back = "10" if hdrnet else "12"
    frames_ns_front = "7" if hdrnet else "8"
    merge = "0" if hdrnet else "1"
    livehdr = "1" if hdrnet else "2"

    lines = [
        "<?xml version='1.0' encoding='utf-8' standalone='yes' ?>",
        "<map>",
        # --- identity (informational; processing does not depend on these) ---
        S("pref_gcam_version_key", "8.4"),
        S("info_brand_key", "POCO"),
        S("info_manuf_key", "Xiaomi"),
        S("info_device_key", "camellian"),
        S("info_model_key", "M2103K19PG"),
        S("info_board_key", "camellia"),
        S("info_hardware_key", "mt6833"),
        S("info_android_version_key", "13"),
        S("info_sdk_key", "33"),
        S(
            "info_fingerprint_key",
            "POCO/camellian_global/camellian:13/TP1A.220624.014/V14.0.6.0.TKSMIXM:user/release-keys",
        ),
        S("pref_prefix_key", "M3Pro_"),
        S("pref_watermark_type_key", "0"),
        S("pref_photo_watermark_key", "0"),
        S("pref_watermark_title_key", ""),
        S("pref_lens_title_key", ""),
        S("pref_lens_title_key_0", "Main OV48B 12MP"),
        S("pref_lens_title_key_1", "Selfie OV8856 8MP"),
        S("pref_lens_title_key_2", "Macro"),
        S("pref_lens_title_key_3", "Front"),
        # --- cameras: main + front only (2MP macro/depth crash and add no quality) ---
        SET("pref_camera_id_list_key", ["0", "1"]),
        SET("pref_all_camera_id_list_key", ["0", "1"]),
        S("pref_aux_key", "0"),
        S("pref_aux_front_key", "0"),
        S("pref_gcam_lens_logic_key", "0"),
        S("pref_48m_key", "0"),
        S("pref_upscale_key", "0"),
        S("pref_fix_resolution_key", "0"),
        S("pref_camera_resolution", "full"),
        S("pref_camera_picturesize_back_key", "4000x3000"),
        S("pref_camera_picturesize_front_key", "3264x2448"),
        S("pref_qjpg_key", "97"),
        S("pref_raw_key", "0"),
        S("pref_camera_raw_output_key", "0"),
        S("pref_camera_raw_output_option_available_key", "1"),
        S("pref_p3_key", "1"),
        # --- HDR / merge / frames (Dimensity 700 + 4/6 GB RAM) ---
        S("pref_camera_hdr_plus_key", hdr_plus),
        S("pref_camera_hdrplus_option_available_key", "1"),
        S("pref_hdrnet_key", "1" if hdrnet else "0"),
        S("pref_livehdr_key", livehdr),
        S("pref_merge_key", merge),
        S("pref_shasta_key", "0"),
        S("pref_frame_count_key", frames_enh_back),
        S("pref_frame_count_key_0", frames_enh_back),
        S("pref_frame_count_key_1", frames_enh_front),
        S("pref_frame_count_key_3", frames_enh_front),
        S("pref_frame_count_zsl_key", frames_zsl),
        S("pref_frame_count_ns_key", frames_ns_back),
        S("pref_frame_count_ns_key_0", frames_ns_back),
        S("pref_frame_count_ns_key_1", frames_ns_front),
        S("pref_frame_count_ns_key_3", frames_ns_front),
        S("pref_frame_count_astro_key", "6"),
        S("pref_frame_count_astro_key_0", "6"),
        S("pref_frame_count_astro_key_1", "5"),
        S("pref_frame_count_astro_key_3", "5"),
        S("pref_expcomp_key", "0"),
        S("pref_expcomp_key_0", "0"),
        S("pref_expcomp_key_1", "1"),
        S("pref_expcomp_key_3", "1"),
        S("pref_expcomp_ns_key", "0"),
        S("pref_expcomp_ns_key_0", "2"),
        S("pref_expcomp_ns_key_1", "2"),
        S("pref_expcomp_ns_key_3", "2"),
        S("pref_expcomp_portrait_key", "0"),
        S("pref_expcomp_portrait_key_0", "0"),
        S("pref_expcomp_portrait_key_1", "1"),
        S("pref_expcomp_portrait_key_3", "1"),
        S("pref_exposure_control_key", "1"),
        # --- AWB / noise / black level ---
        # AWB 8 = IMX363 (Pixel 4/5) — most reliable "Pixel" look on OV48B.
        # Noise model 0 = system (LMC 8.4 R14+). Hexagon OFF (MediaTek).
        S("pref_awb_key", "8"),
        S("pref_awb_key_0", "8"),
        S("pref_awb_key_1", "8"),
        S("pref_awb_key_3", "8"),
        S("pref_awb_switch_key_0", "1"),
        S("pref_awbratio_key", "2"),
        S("lib_pref_awb_key", "8"),
        S("lib_pref_awbratio_key", "0"),
        S("pref_noise_model_key", "0"),
        S("pref_iso_noise_key", "0"),
        S("pref_iso_noise_coeff_key", "0.5"),
        S("pref_hexagon_key", "0"),
        S("pref_ois_key", "0"),
        S("pref_hot_pixel_key", "2"),
        S("pref_dotfix_key", "0"),
        S("pref_dotfix_key_0", "0"),
        S("pref_dotfix_key_1", "0"),
        S("pref_black_level_key", "0"),
        S("pref_black_level_dynamic_key", "0"),
        S("black_level_0_key", "64.0"),
        S("black_level_1_key", "64.0"),
        S("black_level_2_key", "64.0"),
        S("black_level_3_key", "64.0"),
        S("pref_white_level_key", "0"),
        S("pref_color_transform_key", "14"),
        S("pref_color_transform_key_0", "14"),
        S("pref_color_transform_key_1", "14"),
        S("pref_color_transform_key_3", "14"),
        S("lib_pref_color_transform_key", "14"),
        S("lib_gamma_curve_preset_key", "Off (as in library)"),
        S("lib_tone_curve_preset_key", "Off (as in library)"),
        S("pref_fix_awbgains_key_0", "1"),
        S("pref_fix_awbgains_key_3", "1"),
        S("pref_fix_spatial_gain_map_key", "0"),
        S("pref_lost_exif_key", "1"),
        # MTK OV48B / OV8856 often run a touch green-yellow. Pull G down, B up a hair.
        S("pref_green_coeff_key", "0.96"),
        S("pref_green_coeff_key_0", "0.96"),
        S("pref_green_coeff_key_1", "0.95"),
        S("pref_green_coeff_key_3", "0.95"),
        S("pref_red_coeff_key", "0.99"),
        S("pref_red_coeff_key_0", "0.99"),
        S("pref_red_coeff_key_1", "0.97"),
        S("pref_red_coeff_key_3", "0.97"),
        S("pref_blue_coeff_key", "1.02"),
        S("lib_pref_green_coeff_key", "0.96"),
        S("lib_pref_red_coeff_key", "0.99"),
        S("lib_pref_blue_coeff_key", "1.02"),
        S("pref_awb_rg_coeff_key", "1.0"),
        S("pref_awb_bg_coeff_key", "1.0"),
        S("lib_pref_awb_rg_coeff_key", "1.0"),
        S("lib_pref_awb_bg_coeff_key", "1.0"),
        S("pref_satcct_key", "1.0"),
        S("pref_satcct_r_key", "1.0"),
        S("pref_satcct_g_key", "1.0"),
        S("pref_satcct_b_key", "1.0"),
        S("pref_satcct_c_key", "1.0"),
        S("pref_satcct_y_key", "1.0"),
        S("lib_pref_satcct_key", "1.0"),
        S("lib_pref_satcct_r_key", "1.0"),
        S("lib_pref_satcct_g_key", "1.0"),
        S("lib_pref_satcct_b_key", "1.0"),
        S("lib_pref_satcct_c_key", "1.0"),
        S("lib_pref_satcct_y_key", "1.0"),
        S("pref_cct_wb_intensity_key", "1.0"),
        S("pref_cct_wb_offset_key", "1.0"),
        S("lib_pref_cct_wb_intensity_key", "1.0"),
        S("lib_pref_cct_wb_offset_key", "1.0"),
        S("pref_global_hue_key", "0"),
        S("pref_r_hue_key", "0"),
        S("pref_g_hue_key", "0"),
        S("pref_b_hue_key", "0"),
        S("pref_y_hue_key", "0"),
        S("pref_c_hue_key", "0"),
        S("lib_pref_global_hue_key", "0"),
        S("lib_pref_r_hue_key", "0"),
        S("lib_pref_g_hue_key", "0"),
        S("lib_pref_b_hue_key", "0"),
        S("lib_pref_y_hue_key", "0"),
        S("lib_pref_c_hue_key", "0"),
        S("pref_tune_coeff_key", "0.5"),
        S("pref_tune_model_key", "0"),
        # --- focus / AF ---
        S("pref_af_mode", "0"),
        S("pref_af_mode_back", "3"),
        S("pref_af_mode_front", "0"),
        S("pref_track_focus_key", "0"),
        S("pref_manual_focus_slider_key", "1"),
        S("pref_focus_value_key", "10"),
        S("pref_focus_lock_time_key", "6"),
        S("pref_manual_focus_near_key", "14.29"),
        S("pref_manual_focus_far_key", "0.21"),
        S("pref_manual_focus_median_key", "0.833"),
        S("pref_manual_focus_infinity_key", "0.12"),
        S("pref_max_zoom_key", "20"),
        S("pref_zoom_key", "0"),
        S("pref_pzoom_disable_key", "0"),
        S("pref_double_tap_key", "zoom"),
        # --- video: hardware max is 1080p30. 4K / high-fps slo-mo crash on D700. ---
        S("pref_video_resolution", "RES_1080P"),
        S("pref_video_aspect_ratio", "SIXTEEN_BY_NINE"),
        S("pref_video_fps_p2018_key", "FPS_30"),
        S("pref_video_fps_cm_key", "FPS_30"),
        S("pref_video_fps_4k_key", "FPS_30"),
        S("pref_4k_timelapse_key", "0"),
        S("pref_bitrate_key", "0"),
        S("pref_audio_zoom_key", "0"),
        S("pref_ext_mic_key", "0"),
        S("pref_imax_audio_enabled_key", "0"),
        S("pref_micro_video_key", "0"),
        S("pref_micro_mode", "0"),
        S("pref_motion_key", "0"),
        S("pref_camera_kepler_enabled_key", "0"),
        S("pref_enabled_catshark_key", "0"),
        S("pref_camera_dynamic_depth_enabled_key", "0"),
        S("pref_mars_enabled", "0"),
        S("pref_camera_astro", "-1"),
        # --- opmodes (0 = auto / default session; do not force Pixel sessions on MTK) ---
        S("pref_opmode_photo_key", "0"),
        S("pref_opmode_ns_key", "0"),
        S("pref_opmode_portrait_key", "0"),
        S("pref_opmode_video_key", "0"),
        S("pref_opmode_slowmo_key", "0"),
        S("pref_opmode_time_lapse_key", "0"),
        S("pref_opmode_amber_key", "0"),
        S("pref_manual_opmode_photo_key", "0"),
        S("pref_manual_opmode_ns_key", "0"),
        S("pref_manual_opmode_portrait_key", "0"),
        S("pref_manual_opmode_video_key", "0"),
        S("pref_manual_opmode_slowmo_key", "0"),
        S("pref_manual_opmode_time_lapse_key", "0"),
        S("pref_manual_opmode_amber_key", "0"),
        S("pref_stream_opmode_key", "0"),
        S("pref_device_key", "0"),
        S("pref_device_key_0", "0"),
        S("pref_device_key_1", "0"),
        S("pref_device_key_2", "0"),
        S("pref_device_key_3", "0"),
        S("pref_device_key_4", "0"),
        S("pref_model_key", "0"),
        S("pref_model_key_0", "0"),
        S("pref_model_key_1", "0"),
        S("pref_model_key_2", "0"),
        S("pref_model_key_3", "0"),
        S("pref_model_key_4", "0"),
        # --- UI / behaviour ---
        S("pref_camera_selfie_mirror_key", "1"),
        S("pref_camera_sounds_key", "1"),
        S("pref_camera_single_shot_sound_key", "0"),
        S("pref_vibro_key", "1"),
        S("pref_volume_key_action", "shutter"),
        S("pref_shutter_key", "1"),
        S("pref_camera_grid_lines_mode", "0"),
        S("pref_camera_grid_lines_mode_new", "0"),
        S("pref_camera_recordlocation_key", "0"),
        S("pref_gallery_key", "1"),
        S("pref_sunlight_key", "1"),
        S("pref_antibanding_key", "1"),
        S("pref_camera_front_flashmode_key", "off"),
        S("pref_camera_selfie_flashmode_key", "0"),
        S("pref_chameleon_control_key", "0"),
        S("pref_camera_coach_key", "0"),
        S("pref_dirty_lens_detector_key", "0"),
        S("pref_camera_advice_settings", "0"),
        S("pref_camera_cd_indicator_enabled_key", "1"),
        S("pref_camera_enable_iris", "0"),
        S("pref_menu_value_key", "1"),
        S("pref_photo_grayscale_key", "0"),
        S("pref_switch_front_restart_key", "0"),
        S("pref_camera_switch_position_key", "embed"),
        S("pref_mode_vesper_level", "1"),
        S("pref_mode_vesperad_option", "0"),
        S("pref_beauty_detail_key", "1"),
        S("pref_beauty_microdermabrasion_key", "0"),
        S("pref_saperture", "0"),
        S("pref_manual_iso_noise_key", "6400"),
        S("pref_pckstream_yuv_analysis", "0"),
        S("pref_pckstream_raw_hdrplus", "1"),
        S("pref_pckstream_viewfinder", "1"),
        S("pref_preview_key", "0"),
        S("pref_preview_key_0", "256"),
        S("pref_preview_key_1", "256"),
        S("pref_preview_key_3", "256"),
        S("pref_c2a_key", "0"),
        S("pref_c2a_key_0", "0"),
        S("pref_c2a_key_1", "0"),
        S("pref_c2a_key_3", "0"),
        S("pref_xml_path_key", "/LMC8.4/"),
        S("lib_profile_title_key", "Daily Natural"),
        S("lib_patch_profile_key", "0"),
        S("patch_profile_key_0", "0"),
        S("patch_profile_key_1", "8"),
        S("custom_lib_open_key", ""),
        S("pref_enable_log_file_key", "0"),
        S("pref_update_color_online_key", "0"),
        S("pref_storage_saver_auto_disable", "0"),
        S("dev_setting_filter_key", "gl"),
        # --- developer flags: MediaTek Dimensity 700 stability ---
        B("camera.cuttle.glpreview", False),
        B("camcorder.covec_video", False),
        B("camera.pck_large_yuv", False),
        B("camera.pck_analysis_yuv", False),
        B("camera.mts_gpu_yuv", False),
        B("force_cpu_processing", False),
        B("hdrnet_enabled", hdrnet),
        B("camera.chameleon.enabled", False),
        B("camera.include_ultra_short_frame", False),
        B("camera.enable_sideline", False),
        B("camera.front_torch_request", False),
        B("camera.extra_zoom_linger", False),
        B("camera.gouda.object_portrait", False),
        B("cuttle.astro_force", True),
        B("autotimer_tutorial_shown", True),
    ]

    for pid in range(12):
        lines.extend(lib_block(pid, PROFILES[pid]))

    # A few extra selfie-stream keys used when front night/beauty kicks in
    for extra in (
        ("lib_profile_title_key_p8_1", "Selfie Night"),
        ("lib_sharpness_a_key_p8_1", "1.0625"),
        ("lib_luma_a_key_p8_1", "1.3125"),
        ("lib_luma_b_key_p8_1", "1.25"),
        ("lib_chroma_a_key_p8_1", "1.4375"),
        ("lib_chroma_b_key_p8_1", "1.3125"),
        ("lib_saturation_key_p8_1", "1.0625"),
        ("lib_lutnoisefix_key_p8_1", "4.0 (ON)"),
        ("lib_iso_key_p8_1", "3200"),
        ("lib_pref_color_transform_key_p8_1", "14"),
        ("lib_highlight_fix_key_p8_1", "1"),
        ("lib_highlight_fix_2_key_p8_1", "1"),
        ("lib_highlight_fix_3_key_p8_1", "1"),
    ):
        lines.append(S(*extra))

    lines.append("</map>")
    lines.append("")
    return "\n".join(lines)


def main():
    quality = OUT / "LMC8.4_R18_PocoM3Pro5G_Camellia_Quality_v1.0.xml"
    fast = OUT / "LMC8.4_R18_PocoM3Pro5G_Camellia_Fast_v1.0.xml"
    quality.write_text(build("quality"), encoding="utf-8")
    fast.write_text(build("fast"), encoding="utf-8")
    print(f"wrote {quality} ({quality.stat().st_size} bytes)")
    print(f"wrote {fast} ({fast.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
